# This file is automatically generated from remake_species_data.yml.whisker:
# edit the file there (or the files that it includes).

filterToBAER <- function(...) {
  filterBySpecies("BAER", ...)
}

CalculateInvestmentForBAER <- function(...) {
  CalculateInvestmentForSpecies("BAER", ...)
}

CalculateReproductiveCostsForBAER <- function(...) {
  ReproductiveCosts("BAER", ...)
}

CalculateGrowthForBAER <- function(...) {
  growth_calculations("BAER", ...)
}

print_xtable_BAER <- function(...) {
  print_xtable_for_species("BAER", ...)
}

filterToBOLE <- function(...) {
  filterBySpecies("BOLE", ...)
}

CalculateInvestmentForBOLE <- function(...) {
  CalculateInvestmentForSpecies("BOLE", ...)
}

CalculateReproductiveCostsForBOLE <- function(...) {
  ReproductiveCosts("BOLE", ...)
}

CalculateGrowthForBOLE <- function(...) {
  growth_calculations("BOLE", ...)
}

print_xtable_BOLE <- function(...) {
  print_xtable_for_species("BOLE", ...)
}

filterToCOER <- function(...) {
  filterBySpecies("COER", ...)
}

CalculateInvestmentForCOER <- function(...) {
  CalculateInvestmentForSpecies("COER", ...)
}

CalculateReproductiveCostsForCOER <- function(...) {
  ReproductiveCosts("COER", ...)
}

CalculateGrowthForCOER <- function(...) {
  growth_calculations("COER", ...)
}

print_xtable_COER <- function(...) {
  print_xtable_for_species("COER", ...)
}

filterToEPMI <- function(...) {
  filterBySpecies("EPMI", ...)
}

CalculateInvestmentForEPMI <- function(...) {
  CalculateInvestmentForSpecies("EPMI", ...)
}

CalculateReproductiveCostsForEPMI <- function(...) {
  ReproductiveCosts("EPMI", ...)
}

CalculateGrowthForEPMI <- function(...) {
  growth_calculations("EPMI", ...)
}

print_xtable_EPMI <- function(...) {
  print_xtable_for_species("EPMI", ...)
}

filterToGRBU <- function(...) {
  filterBySpecies("GRBU", ...)
}

CalculateInvestmentForGRBU <- function(...) {
  CalculateInvestmentForSpecies("GRBU", ...)
}

CalculateReproductiveCostsForGRBU <- function(...) {
  ReproductiveCosts("GRBU", ...)
}

CalculateGrowthForGRBU <- function(...) {
  growth_calculations("GRBU", ...)
}

print_xtable_GRBU <- function(...) {
  print_xtable_for_species("GRBU", ...)
}

filterToGRSP <- function(...) {
  filterBySpecies("GRSP", ...)
}

CalculateInvestmentForGRSP <- function(...) {
  CalculateInvestmentForSpecies("GRSP", ...)
}

CalculateReproductiveCostsForGRSP <- function(...) {
  ReproductiveCosts("GRSP", ...)
}

CalculateGrowthForGRSP <- function(...) {
  growth_calculations("GRSP", ...)
}

print_xtable_GRSP <- function(...) {
  print_xtable_for_species("GRSP", ...)
}

filterToHATE <- function(...) {
  filterBySpecies("HATE", ...)
}

CalculateInvestmentForHATE <- function(...) {
  CalculateInvestmentForSpecies("HATE", ...)
}

CalculateReproductiveCostsForHATE <- function(...) {
  ReproductiveCosts("HATE", ...)
}

CalculateGrowthForHATE <- function(...) {
  growth_calculations("HATE", ...)
}

print_xtable_HATE <- function(...) {
  print_xtable_for_species("HATE", ...)
}

filterToHEPU <- function(...) {
  filterBySpecies("HEPU", ...)
}

CalculateInvestmentForHEPU <- function(...) {
  CalculateInvestmentForSpecies("HEPU", ...)
}

CalculateReproductiveCostsForHEPU <- function(...) {
  ReproductiveCosts("HEPU", ...)
}

CalculateGrowthForHEPU <- function(...) {
  growth_calculations("HEPU", ...)
}

print_xtable_HEPU <- function(...) {
  print_xtable_for_species("HEPU", ...)
}

filterToLEES <- function(...) {
  filterBySpecies("LEES", ...)
}

CalculateInvestmentForLEES <- function(...) {
  CalculateInvestmentForSpecies("LEES", ...)
}

CalculateReproductiveCostsForLEES <- function(...) {
  ReproductiveCosts("LEES", ...)
}

CalculateGrowthForLEES <- function(...) {
  growth_calculations("LEES", ...)
}

print_xtable_LEES <- function(...) {
  print_xtable_for_species("LEES", ...)
}

filterToPELA <- function(...) {
  filterBySpecies("PELA", ...)
}

CalculateInvestmentForPELA <- function(...) {
  CalculateInvestmentForSpecies("PELA", ...)
}

CalculateReproductiveCostsForPELA <- function(...) {
  ReproductiveCosts("PELA", ...)
}

CalculateGrowthForPELA <- function(...) {
  growth_calculations("PELA", ...)
}

print_xtable_PELA <- function(...) {
  print_xtable_for_species("PELA", ...)
}

filterToPEPU <- function(...) {
  filterBySpecies("PEPU", ...)
}

CalculateInvestmentForPEPU <- function(...) {
  CalculateInvestmentForSpecies("PEPU", ...)
}

CalculateReproductiveCostsForPEPU <- function(...) {
  ReproductiveCosts("PEPU", ...)
}

CalculateGrowthForPEPU <- function(...) {
  growth_calculations("PEPU", ...)
}

print_xtable_PEPU <- function(...) {
  print_xtable_for_species("PEPU", ...)
}

filterToPHPH <- function(...) {
  filterBySpecies("PHPH", ...)
}

CalculateInvestmentForPHPH <- function(...) {
  CalculateInvestmentForSpecies("PHPH", ...)
}

CalculateReproductiveCostsForPHPH <- function(...) {
  ReproductiveCosts("PHPH", ...)
}

CalculateGrowthForPHPH <- function(...) {
  growth_calculations("PHPH", ...)
}

print_xtable_PHPH <- function(...) {
  print_xtable_for_species("PHPH", ...)
}

filterToPILI <- function(...) {
  filterBySpecies("PILI", ...)
}

CalculateInvestmentForPILI <- function(...) {
  CalculateInvestmentForSpecies("PILI", ...)
}

CalculateReproductiveCostsForPILI <- function(...) {
  ReproductiveCosts("PILI", ...)
}

CalculateGrowthForPILI <- function(...) {
  growth_calculations("PILI", ...)
}

print_xtable_PILI <- function(...) {
  print_xtable_for_species("PILI", ...)
}

filterToPUTU <- function(...) {
  filterBySpecies("PUTU", ...)
}

CalculateInvestmentForPUTU <- function(...) {
  CalculateInvestmentForSpecies("PUTU", ...)
}

CalculateReproductiveCostsForPUTU <- function(...) {
  ReproductiveCosts("PUTU", ...)
}

CalculateGrowthForPUTU <- function(...) {
  growth_calculations("PUTU", ...)
}

print_xtable_PUTU <- function(...) {
  print_xtable_for_species("PUTU", ...)
}


